### PR TITLE
Fix typos and preview errors for Embed page

### PR DESCRIPTION
**Pull request by candideu**

### CODE REVIEW

**Review by Bad3r — CHANGES_REQUESTED** [review]
Thank you for the contribution!
Would you mind removing the empty lines?

There are multiple lines in the document that are empty


```
-
```

**Comment by candideu** [comment]
> Thank you for the contribution! Would you mind removing the empty lines?
> 
> There are multiple lines in the document that are empty
> 
> ```
> -
> ```

@Bad3r Should be fixed now.

**Review by Bad3r — CHANGES_REQUESTED** [review]
There are few things in the formatting that needs to be changed. I made a PR to your branch with my modified version of this doc.
- PR: https://github.com/candideu/docs/pull/1
- View live version: https://beta.hacklog.sh/#/page/embed%20media%20-%20audio%2C%20photos%2C%20videos
- changes:
  - Removed nested level one headers (not recommended)
  - Removed empty lines
  - fixed formatting
  - Fixed typos in Video section
  - fixed Vimeo section

**Comment by Bad3r** [comment]
@candideu any updates? If you want to I can make a separate PR for the changes if you don't have the time.

**Comment by candideu** [comment]
> @candideu any updates? If you want to I can make a separate PR for the changes if you don't have the time.

Hi @Bad3r : I'm still newish to Github Pull Requests, so I didn't realize that I had to merge yours. Did it work?

**Comment by Bad3r** [comment]
> > @candideu any updates? If you want to I can make a separate PR for the changes if you don't have the time.
> 
> 
> 
> Hi @Bad3r : I'm still newish to Github Pull Requests, so I didn't realize that I had to merge yours. Did it work?

No worries yes it did! Thank you so much for the contribution. I already linked few users to this page to answer their questions. Hopefully it will be merged soon. 

@tiensonqin LGTM

**Review by Bad3r — APPROVED** [review]

**Comment by larrykollar** [comment]
On the new line 30, there's only two backticks instead of three.

In general, is there a tag we can use for syntax-highlighting the Hiccup examples? cljs, maybe?

**Comment by Bad3r** [comment]
@larrykollar Thanks for caching it! I was also able to add syntax highlight.   
@candideu Please merge my new PR. candideu#2

**Comment by Bad3r** [comment]
@candideu I closed the PR with the conflict and made a new one. Sorry for the late response. Please merge it when you get a chance. Thank you!

**Comment by candideu** [comment]
> @candideu I closed the PR with the conflict and made a new one. Sorry for the late response. Please merge it when you get a chance. Thank you!

Okay, I think I merged it. Please let me know if that works.

**Comment by Bad3r** [comment]
Great thank you!

**Review by Bad3r — APPROVED** [review]
LGTM

**Pull request merged**
